/* MTI_DPI */

/*
 * Copyright 2002-2013 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linuxpe'
 */
#ifndef INCLUDED_DPI
#define INCLUDED_DPI

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
connectSocket();

DPI_LINK_DECL DPI_DLLESPEC
int
eject(
    int* id,
    int* vc);

DPI_LINK_DECL DPI_DLLESPEC
void
exitSocket();

DPI_LINK_DECL DPI_DLLESPEC
void
inject();

DPI_LINK_DECL DPI_DLLESPEC
void
nextCycle(
    int speedup);

DPI_LINK_DECL DPI_DLLESPEC
void
queueFlit(
    int pid,
    int fid,
    int source,
    int destination,
    int vc,
    int head,
    int tail);

DPI_LINK_DECL DPI_DLLESPEC
int
receive_credit(
    int node,
    int vc);

DPI_LINK_DECL DPI_DLLESPEC
void
send_credit(
    int node,
    int vc,
    int credit);

#endif 
