#!/bin/bash

VSIM_DIR=/home/mohamed/altera/14.0/modelsim_ase/include 
BOOKSIM_DIR='../../booksim'
DESIGN_DIR=`pwd`

#remake booksim
cd $BOOKSIM_DIR
make
cd $DESIGN_DIR

#create work library
rm -rf work
vlib work

#######################
#compile verilog files
#######################

#compile the rtl interface that talks to booksim's socket interface
vlog -dpiheader $BOOKSIM_DIR/dpi.h $BOOKSIM_DIR/rtl_interface.sv

#compile your design files (and testbenches) here
vlog testbench.sv

#########################################
#recompile the booksim socket interface
########################################

g++ -c -fPIC -m32 -I$VSIM_DIR $BOOKSIM_DIR/booksim_interface.cpp
g++ -shared -Bsymbolic -fPIC -m32 -o booksim_interface.so booksim_interface.o

###############################
#run booksim in a new terminal
###############################

gnome-terminal -e $BOOKSIM_DIR/booksim\ noc_config &

################
#run simulation
################

if [ "$1" == "vsim" ]; then
	vsim -sv_lib booksim_interface testbench -do wave.do 
else
	vsim -c -sv_lib booksim_interface testbench -do "run -all"
fi

#########
#cleanup
#########

killall booksim
killall vsim
killall vsimk

rm -r work
rm transcript
rm socket
rm *.out
rm *.o *.so *.wlf *.vstf
